# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.11

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /ausr/local/bin/cmake

# The command to remove a file.
RM = /ausr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/student/Documents/Davletshin/Simple_Geant4_example

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/student/Documents/Davletshin/Simple_Geant4_example

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/ausr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/ausr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/ausr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/ausr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/ausr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/ausr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/ausr/local/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/ausr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/Documents/Davletshin/Simple_Geant4_example/CMakeFiles /home/student/Documents/Davletshin/Simple_Geant4_example/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/student/Documents/Davletshin/Simple_Geant4_example/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ExampleG41

# Build rule for target.
ExampleG41: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExampleG41
.PHONY : ExampleG41

# fast build rule for target.
ExampleG41/fast:
	$(MAKE) -f CMakeFiles/ExampleG41.dir/build.make CMakeFiles/ExampleG41.dir/build
.PHONY : ExampleG41/fast

ExG4.o: ExG4.cc.o

.PHONY : ExG4.o

# target to build an object file
ExG4.cc.o:
	$(MAKE) -f CMakeFiles/ExampleG41.dir/build.make CMakeFiles/ExampleG41.dir/ExG4.cc.o
.PHONY : ExG4.cc.o

ExG4.i: ExG4.cc.i

.PHONY : ExG4.i

# target to preprocess a source file
ExG4.cc.i:
	$(MAKE) -f CMakeFiles/ExampleG41.dir/build.make CMakeFiles/ExampleG41.dir/ExG4.cc.i
.PHONY : ExG4.cc.i

ExG4.s: ExG4.cc.s

.PHONY : ExG4.s

# target to generate assembly for a file
ExG4.cc.s:
	$(MAKE) -f CMakeFiles/ExampleG41.dir/build.make CMakeFiles/ExampleG41.dir/ExG4.cc.s
.PHONY : ExG4.cc.s

source/ExG4ActionInitialization01.o: source/ExG4ActionInitialization01.cc.o

.PHONY : source/ExG4ActionInitialization01.o

# target to build an object file
source/ExG4ActionInitialization01.cc.o:
	$(MAKE) -f CMakeFiles/ExampleG41.dir/build.make CMakeFiles/ExampleG41.dir/source/ExG4ActionInitialization01.cc.o
.PHONY : source/ExG4ActionInitialization01.cc.o

source/ExG4ActionInitialization01.i: source/ExG4ActionInitialization01.cc.i

.PHONY : source/ExG4ActionInitialization01.i

# target to preprocess a source file
source/ExG4ActionInitialization01.cc.i:
	$(MAKE) -f CMakeFiles/ExampleG41.dir/build.make CMakeFiles/ExampleG41.dir/source/ExG4ActionInitialization01.cc.i
.PHONY : source/ExG4ActionInitialization01.cc.i

source/ExG4ActionInitialization01.s: source/ExG4ActionInitialization01.cc.s

.PHONY : source/ExG4ActionInitialization01.s

# target to generate assembly for a file
source/ExG4ActionInitialization01.cc.s:
	$(MAKE) -f CMakeFiles/ExampleG41.dir/build.make CMakeFiles/ExampleG41.dir/source/ExG4ActionInitialization01.cc.s
.PHONY : source/ExG4ActionInitialization01.cc.s

source/ExG4DetectorConstruction01.o: source/ExG4DetectorConstruction01.cc.o

.PHONY : source/ExG4DetectorConstruction01.o

# target to build an object file
source/ExG4DetectorConstruction01.cc.o:
	$(MAKE) -f CMakeFiles/ExampleG41.dir/build.make CMakeFiles/ExampleG41.dir/source/ExG4DetectorConstruction01.cc.o
.PHONY : source/ExG4DetectorConstruction01.cc.o

source/ExG4DetectorConstruction01.i: source/ExG4DetectorConstruction01.cc.i

.PHONY : source/ExG4DetectorConstruction01.i

# target to preprocess a source file
source/ExG4DetectorConstruction01.cc.i:
	$(MAKE) -f CMakeFiles/ExampleG41.dir/build.make CMakeFiles/ExampleG41.dir/source/ExG4DetectorConstruction01.cc.i
.PHONY : source/ExG4DetectorConstruction01.cc.i

source/ExG4DetectorConstruction01.s: source/ExG4DetectorConstruction01.cc.s

.PHONY : source/ExG4DetectorConstruction01.s

# target to generate assembly for a file
source/ExG4DetectorConstruction01.cc.s:
	$(MAKE) -f CMakeFiles/ExampleG41.dir/build.make CMakeFiles/ExampleG41.dir/source/ExG4DetectorConstruction01.cc.s
.PHONY : source/ExG4DetectorConstruction01.cc.s

source/ExG4EventAction01.o: source/ExG4EventAction01.cc.o

.PHONY : source/ExG4EventAction01.o

# target to build an object file
source/ExG4EventAction01.cc.o:
	$(MAKE) -f CMakeFiles/ExampleG41.dir/build.make CMakeFiles/ExampleG41.dir/source/ExG4EventAction01.cc.o
.PHONY : source/ExG4EventAction01.cc.o

source/ExG4EventAction01.i: source/ExG4EventAction01.cc.i

.PHONY : source/ExG4EventAction01.i

# target to preprocess a source file
source/ExG4EventAction01.cc.i:
	$(MAKE) -f CMakeFiles/ExampleG41.dir/build.make CMakeFiles/ExampleG41.dir/source/ExG4EventAction01.cc.i
.PHONY : source/ExG4EventAction01.cc.i

source/ExG4EventAction01.s: source/ExG4EventAction01.cc.s

.PHONY : source/ExG4EventAction01.s

# target to generate assembly for a file
source/ExG4EventAction01.cc.s:
	$(MAKE) -f CMakeFiles/ExampleG41.dir/build.make CMakeFiles/ExampleG41.dir/source/ExG4EventAction01.cc.s
.PHONY : source/ExG4EventAction01.cc.s

source/ExG4PrimaryGeneratorAction01.o: source/ExG4PrimaryGeneratorAction01.cc.o

.PHONY : source/ExG4PrimaryGeneratorAction01.o

# target to build an object file
source/ExG4PrimaryGeneratorAction01.cc.o:
	$(MAKE) -f CMakeFiles/ExampleG41.dir/build.make CMakeFiles/ExampleG41.dir/source/ExG4PrimaryGeneratorAction01.cc.o
.PHONY : source/ExG4PrimaryGeneratorAction01.cc.o

source/ExG4PrimaryGeneratorAction01.i: source/ExG4PrimaryGeneratorAction01.cc.i

.PHONY : source/ExG4PrimaryGeneratorAction01.i

# target to preprocess a source file
source/ExG4PrimaryGeneratorAction01.cc.i:
	$(MAKE) -f CMakeFiles/ExampleG41.dir/build.make CMakeFiles/ExampleG41.dir/source/ExG4PrimaryGeneratorAction01.cc.i
.PHONY : source/ExG4PrimaryGeneratorAction01.cc.i

source/ExG4PrimaryGeneratorAction01.s: source/ExG4PrimaryGeneratorAction01.cc.s

.PHONY : source/ExG4PrimaryGeneratorAction01.s

# target to generate assembly for a file
source/ExG4PrimaryGeneratorAction01.cc.s:
	$(MAKE) -f CMakeFiles/ExampleG41.dir/build.make CMakeFiles/ExampleG41.dir/source/ExG4PrimaryGeneratorAction01.cc.s
.PHONY : source/ExG4PrimaryGeneratorAction01.cc.s

source/ExG4RunAction01.o: source/ExG4RunAction01.cc.o

.PHONY : source/ExG4RunAction01.o

# target to build an object file
source/ExG4RunAction01.cc.o:
	$(MAKE) -f CMakeFiles/ExampleG41.dir/build.make CMakeFiles/ExampleG41.dir/source/ExG4RunAction01.cc.o
.PHONY : source/ExG4RunAction01.cc.o

source/ExG4RunAction01.i: source/ExG4RunAction01.cc.i

.PHONY : source/ExG4RunAction01.i

# target to preprocess a source file
source/ExG4RunAction01.cc.i:
	$(MAKE) -f CMakeFiles/ExampleG41.dir/build.make CMakeFiles/ExampleG41.dir/source/ExG4RunAction01.cc.i
.PHONY : source/ExG4RunAction01.cc.i

source/ExG4RunAction01.s: source/ExG4RunAction01.cc.s

.PHONY : source/ExG4RunAction01.s

# target to generate assembly for a file
source/ExG4RunAction01.cc.s:
	$(MAKE) -f CMakeFiles/ExampleG41.dir/build.make CMakeFiles/ExampleG41.dir/source/ExG4RunAction01.cc.s
.PHONY : source/ExG4RunAction01.cc.s

source/ExG4SteppingAction01.o: source/ExG4SteppingAction01.cc.o

.PHONY : source/ExG4SteppingAction01.o

# target to build an object file
source/ExG4SteppingAction01.cc.o:
	$(MAKE) -f CMakeFiles/ExampleG41.dir/build.make CMakeFiles/ExampleG41.dir/source/ExG4SteppingAction01.cc.o
.PHONY : source/ExG4SteppingAction01.cc.o

source/ExG4SteppingAction01.i: source/ExG4SteppingAction01.cc.i

.PHONY : source/ExG4SteppingAction01.i

# target to preprocess a source file
source/ExG4SteppingAction01.cc.i:
	$(MAKE) -f CMakeFiles/ExampleG41.dir/build.make CMakeFiles/ExampleG41.dir/source/ExG4SteppingAction01.cc.i
.PHONY : source/ExG4SteppingAction01.cc.i

source/ExG4SteppingAction01.s: source/ExG4SteppingAction01.cc.s

.PHONY : source/ExG4SteppingAction01.s

# target to generate assembly for a file
source/ExG4SteppingAction01.cc.s:
	$(MAKE) -f CMakeFiles/ExampleG41.dir/build.make CMakeFiles/ExampleG41.dir/source/ExG4SteppingAction01.cc.s
.PHONY : source/ExG4SteppingAction01.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... install/local"
	@echo "... ExampleG41"
	@echo "... install"
	@echo "... list_install_components"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... ExG4.o"
	@echo "... ExG4.i"
	@echo "... ExG4.s"
	@echo "... source/ExG4ActionInitialization01.o"
	@echo "... source/ExG4ActionInitialization01.i"
	@echo "... source/ExG4ActionInitialization01.s"
	@echo "... source/ExG4DetectorConstruction01.o"
	@echo "... source/ExG4DetectorConstruction01.i"
	@echo "... source/ExG4DetectorConstruction01.s"
	@echo "... source/ExG4EventAction01.o"
	@echo "... source/ExG4EventAction01.i"
	@echo "... source/ExG4EventAction01.s"
	@echo "... source/ExG4PrimaryGeneratorAction01.o"
	@echo "... source/ExG4PrimaryGeneratorAction01.i"
	@echo "... source/ExG4PrimaryGeneratorAction01.s"
	@echo "... source/ExG4RunAction01.o"
	@echo "... source/ExG4RunAction01.i"
	@echo "... source/ExG4RunAction01.s"
	@echo "... source/ExG4SteppingAction01.o"
	@echo "... source/ExG4SteppingAction01.i"
	@echo "... source/ExG4SteppingAction01.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

